### ISSUE TITLE
NPC Killing Itself

### ISSUE THREAD

**Issue by xeryax** [Remod-org/HumanNPC#2]
My human NPCs are killing themselves!!! Its funny as hell, so i am not too upset about it... but... kinda messes with the story.

I am trying to make a zombiekiller to protect my other Story/NPCs, here is his config.
{
      "userid": 1133117860,
      "displayName": "Robocop",
      "invulnerability": false,
      "health": 1000.0,
      "respawn": true,
      "respawnSeconds": 120.0,
      "spawnInfo": {
        "position": "-130.0731 12.26514 1323.279",
        "rotation": "0.1231967 0.7964241 -0.1733141 0.5661213"
      },
      "waypoint": null,
      "collisionRadius": 8.0,
      "spawnkit": "shredder",
      "damageAmount": 80.0,
      "damageDistance": 35.0,
      "damageInterval": 0.1,
      "attackDistance": 60.0,
      "maxDistance": 300.0,
      "hostile": false,
      "ahostile": true,
      "speed": 2.0,
      "stopandtalk": false,
      "stopandtalkSeconds": 3.0,
      "enable": true,
      "persistent": true,
      "lootable": false,
      "hitchance": 0.75,
      "reloadDuration": 0.1,
      "needsAmmo": false,
      "dropWeapon": true,
      "defend": true,
      "evade": false,
      "follow": true,
      "followtime": 15.0,
      "evdist": 15.0,
      "allowsit": false,
      "allowride": false,
      "band": 0.0,
      "message_hello": null,
      "message_bye": null,
      "message_use": null,
      "message_hurt": null,
      "message_kill": null,
      "protections": {
        "Generic": 0.0,
        "Hunger": 0.0,
        "Thirst": 0.0,
        "Cold": 0.0,
        "Drowned": 0.0,
        "Heat": 0.0,
        "Bleeding": 0.0,
        "Poison": 0.0,
        "Suicide": 0.0,
        "Bullet": 0.0,
        "Slash": 0.0,
        "Blunt": 0.0,
        "Fall": 0.0,
        "Radiation": 0.0,
        "Bite": 0.0,
        "Stab": 0.0,
        "Explosion": 0.0,
        "RadiationExposure": 0.0,
        "ColdExposure": 0.0,
        "Decay": 0.0,
        "ElectricShock": 0.0,
        "Arrow": 0.0,
        "AntiVehicle": 0.0,
        "Collision": 0.0,
        "Fun_Water": 0.0
      },
      "hostileTowardsArmed": false,
      "hostileTowardsArmedHard": false,
      "raiseAlarm": true,
      "message_armed": null,
      "message_alarm": null,
      "instrument": null
    }

**Comment by xeryax** [comment]
Since you will be looking at that, a feature request would be to prevent the NPCs from damaging eachother... but i dont know if that is related.

**Comment by RFC1920** [comment]
"invulnerability": true would make it so they cannot be killed.  What do you mean killing themselves.  Each other perhaps?

**Comment by xeryax** [comment]
Apologies, yes, they are killing eachother... i.e. in the config above: "Robocop" is on a team with "AnotherNPC" (not in the config)
when Robocop shoots at a zombie from the halloween event that attacked him, he must have hit AnotherNPC.  This caused those two to start shooting eachother, and ultimately, one of them dying.

I dont necessarily want them to be invulnerable because i want players to be able to kill them... but i dont really want Robocop to run around killing people I have put on his friends list either.

Does that make sense, or did i overcomplicate?

THanks!

**Comment by RFC1920** [comment]
i don't think there is anything built in to manage that.  But, NextGenPVE should allow that level of control.

**Comment by xeryax** [comment]
I will take a look at that!

Thanks RFC!
